# Generated by Django 3.0.4 on 2021-11-22 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0009_auto_20200928_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerchecker',
            name='index',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
