# Generated by Django 3.0.4 on 2021-11-26 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasurehunt', '0010_auto_20211124_1527'),
        ('treasurehunt', '0010_auto_20211122_1016'),
    ]

    operations = [
    ]
